---
# ============================================================================
# Namespace: thingbook
# ----------------------------------------------------------------------------
# A namespace is a logical organization of resources within a single
# Kubernetes cluster.
#
# By using namespaces, a cluster admin may retain control of all cluster
# resources while granting limited administration capabilities within a
# namespace.
# ============================================================================
apiVersion: v1
kind: Namespace
metadata:
  name: thingbook


---
# ============================================================================
# ServiceAccount: thingbook-svc
# ----------------------------------------------------------------------------
# Service accounts provide an identity (and role) for processes within a
# Kubernetes pod.
#
# In this case, we are creating a Service Account in order to give the Pod
# access to the Kubernetes API.
# ============================================================================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: thingbook-svc
  namespace: thingbook


---
# ============================================================================
# ClusterRoleBinding: thingbook-svc -to- cluster-admin
# ----------------------------------------------------------------------------
# A Cluster Role has permissions at the cluster level (vice within a
# namespace).  A Cluster Role Binding allocates a Cluster Role to a Subject
# (such as a ServiceAccount).
#
# Here, we give thingbook-svc ServiceAccount the cluster-admin Cluster Role.
#
# NOTE: This role level far exceeds the actual needs of thingbook-svc, but
#       was the simplest way to get up and running.  THIS SHOULD BE REVIEWED.
# ============================================================================
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: thingbook-svc
subjects:
  - kind: ServiceAccount
    name: thingbook-svc
    namespace: thingbook
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

