name: Node.js CI

on: [ push ]

jobs:
  # --------------------------------------------------------------------------
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
  # --------------------------------------------------------------------------
  docker:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          labels: |
            GITHUB_REF=$GITHUB_REF
            GITHUB_REPOSITORY=$GITHUB_REPOSITORY
            GITHUB_SHA=$GITHUB_SHA
          tags: kerrytjohnson/thingbook-server:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}