name: Node.js CI

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
